image: gradle:alpine

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build

build:
  stage: build
  script:
    - gradle build
    - mv build/libs/*.jar .
  artifacts:
    paths:
      - ./*.jar
