name: SkyBlock
main: me.goodandevil.skyblock.Main
version: 21
api-version: 1.13
description: A unique SkyBlock plugin
author: GoodAndEvil
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI]
loadbefore: [Multiverse-Core]
commands:
    island:
        description: Island command
        aliases: [is]