name: FabledSkyBlock
main: me.goodandevil.skyblock.SkyBlock
version: @version@
api-version: 1.13
description: A unique SkyBlock plugin
author: Songoda
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, Vault, LeaderHeads, EpicSpawners, WildStacker]
loadbefore: [Multiverse-Core]
commands:
    island:
        description: Island command
        aliases: [is]
    skyblock:
        description: Skyblock info command.
