name: SkyBlock
main: me.goodandevil.skyblock.SkyBlock
version: 32
api-version: 1.13
description: A unique SkyBlock plugin
author: GoodAndEvil
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, Vault]
loadbefore: [Multiverse-Core]
commands:
    island:
        description: Island command
        aliases: [is]