name: FabledSkyBlock
main: com.songoda.skyblock.SkyBlock
version: @version@
api-version: 1.13
description: A unique SkyBlock plugin
author: Songoda
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, Vault, Reserve, LeaderHeads, EpicSpawners, WildStacker, UltimateStacker, WorldEdit]
loadbefore: [Multiverse-Core]
commands:
    island:
        description: Island command
        aliases: [is]
    skyblock:
        description: Skyblock info command.
