name: SkyBlock
main: me.goodandevil.skyblock.Main
version: 20
api-version: 1.13
description: A unique SkyBlock plugin
author: GoodAndEvil
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, Multiverse-Core]
commands:
    island:
        description: Island command
        aliases: [is]